# Powerline-Style Starship Configuration
# Classic powerline look with segments

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$ruby\
$golang\
$docker_context\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

add_newline = true

[username]
style_user = "bg:#3B4252 fg:#D8DEE9"
style_root = "bg:#3B4252 fg:#BF616A"
format = '[ $user ]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[@$hostname ](bg:#434C5E fg:#D8DEE9)'
disabled = false

[directory]
style = "bg:#4C566A fg:#D8DEE9"
format = "[ $path ]($style)[$read_only]($read_only_style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#81A1C1 fg:#2E3440"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#88C0D0 fg:#2E3440"
format = '[$all_status$ahead_behind ]($style)'

[nodejs]
symbol = ""
style = "bg:#5E81AC fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#5E81AC fg:#D8DEE9"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "bg:#5E81AC fg:#D8DEE9"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#2E3440 fg:#D8DEE9"
format = '[ $time ]($style)'

[character]
success_symbol = '[](bold fg:#A3BE8C)'
error_symbol = '[](bold fg:#BF616A)'
vicmd_symbol = '[](bold fg:#EBCB8B)'